import { CountryCapitalData } from './types';

/**
 * A comprehensive mapping of ISO 3166-1 alpha-2 country codes to their official capital cities.
 * This data is sourced from official international references and validated for accuracy.
 *
 * @example
 * ```typescript
 * console.log(countryCapitals.US); // "Washington, D.C."
 * console.log(countryCapitals.FR); // "Paris"
 * ```
 */
export const countryCapitals: Readonly<CountryCapitalData> = {
  AD: 'Andorra la Vella',
  AE: 'Abu Dhabi',
  AF: 'Kabul',
  AG: "Saint John's",
  AI: 'The Valley',
  AL: 'Tirana',
  AM: 'Yerevan',
  AO: 'Luanda',
  AR: 'Buenos Aires',
  AS: 'Pago Pago',
  AT: 'Vienna',
  AU: 'Canberra',
  AW: 'Oranjestad',
  AX: 'Mariehamn',
  AZ: 'Baku',
  BA: 'Sarajevo',
  BB: 'Bridgetown',
  BD: 'Dhaka',
  BE: 'Brussels',
  BF: 'Ouagadougou',
  BG: 'Sofia',
  BH: 'Manama',
  BI: 'Gitega',
  BJ: 'Porto-Novo',
  BL: 'Gustavia',
  BM: 'Hamilton',
  BN: 'Bandar Seri Begawan',
  BO: 'Sucre',
  BQ: 'Kralendijk',
  BR: 'Brasília',
  BS: 'Nassau',
  BT: 'Thimphu',
  BW: 'Gaborone',
  BY: 'Minsk',
  BZ: 'Belmopan',
  CA: 'Ottawa',
  CC: 'West Island',
  CD: 'Kinshasa',
  CF: 'Bangui',
  CG: 'Brazzaville',
  CH: 'Bern',
  CI: 'Yamoussoukro',
  CK: 'Avarua',
  CL: 'Santiago',
  CM: 'Yaoundé',
  CN: 'Beijing',
  CO: 'Bogotá',
  CR: 'San José',
  CU: 'Havana',
  CV: 'Praia',
  CW: 'Willemstad',
  CX: 'Flying Fish Cove',
  CY: 'Nicosia',
  CZ: 'Prague',
  DE: 'Berlin',
  DJ: 'Djibouti',
  DK: 'Copenhagen',
  DM: 'Roseau',
  DO: 'Santo Domingo',
  DZ: 'Algiers',
  EC: 'Quito',
  EE: 'Tallinn',
  EG: 'Cairo',
  EH: 'El Aaiún',
  ER: 'Asmara',
  ES: 'Madrid',
  ET: 'Addis Ababa',
  FI: 'Helsinki',
  FJ: 'Suva',
  FK: 'Stanley',
  FM: 'Palikir',
  FO: 'Tórshavn',
  FR: 'Paris',
  GA: 'Libreville',
  GB: 'London',
  GD: "St. George's",
  GE: 'Tbilisi',
  GF: 'Cayenne',
  GG: 'St. Peter Port',
  GH: 'Accra',
  GI: 'Gibraltar',
  GL: 'Nuuk',
  GM: 'Banjul',
  GN: 'Conakry',
  GP: 'Basse-Terre',
  GQ: 'Malabo',
  GR: 'Athens',
  GS: 'King Edward Point',
  GT: 'Guatemala City',
  GU: 'Hagåtña',
  GW: 'Bissau',
  GY: 'Georgetown',
  HK: 'Hong Kong',
  HM: '',
  HN: 'Tegucigalpa',
  HR: 'Zagreb',
  HT: 'Port-au-Prince',
  HU: 'Budapest',
  ID: 'Jakarta',
  IE: 'Dublin',
  IL: 'Jerusalem',
  IM: 'Douglas',
  IN: 'New Delhi',
  IO: 'Diego Garcia',
  IQ: 'Baghdad',
  IR: 'Tehran',
  IS: 'Reykjavík',
  IT: 'Rome',
  JE: 'Saint Helier',
  JM: 'Kingston',
  JO: 'Amman',
  JP: 'Tokyo',
  KE: 'Nairobi',
  KG: 'Bishkek',
  KH: 'Phnom Penh',
  KI: 'South Tarawa',
  KM: 'Moroni',
  KN: 'Basseterre',
  KP: 'Pyongyang',
  KR: 'Seoul',
  KW: 'Kuwait City',
  KY: 'George Town',
  KZ: 'Nur-Sultan',
  LA: 'Vientiane',
  LB: 'Beirut',
  LC: 'Castries',
  LI: 'Vaduz',
  LK: 'Sri Jayawardenepura Kotte',
  LR: 'Monrovia',
  LS: 'Maseru',
  LT: 'Vilnius',
  LU: 'Luxembourg City',
  LV: 'Riga',
  LY: 'Tripoli',
  MA: 'Rabat',
  MC: 'Monaco',
  MD: 'Chișinău',
  ME: 'Podgorica',
  MF: 'Marigot',
  MG: 'Antananarivo',
  MH: 'Majuro',
  MK: 'Skopje',
  ML: 'Bamako',
  MM: 'Naypyidaw',
  MN: 'Ulaanbaatar',
  MO: 'Macau',
  MP: 'Saipan',
  MQ: 'Fort-de-France',
  MR: 'Nouakchott',
  MS: 'Plymouth',
  MT: 'Valletta',
  MU: 'Port Louis',
  MV: 'Malé',
  MW: 'Lilongwe',
  MX: 'Mexico City',
  MY: 'Kuala Lumpur',
  MZ: 'Maputo',
  NA: 'Windhoek',
  NC: 'Nouméa',
  NE: 'Niamey',
  NF: 'Kingston',
  NG: 'Abuja',
  NI: 'Managua',
  NL: 'Amsterdam',
  NO: 'Oslo',
  NP: 'Kathmandu',
  NR: 'Yaren',
  NU: 'Alofi',
  NZ: 'Wellington',
  OM: 'Muscat',
  PA: 'Panama City',
  PE: 'Lima',
  PF: 'Papeete',
  PG: 'Port Moresby',
  PH: 'Manila',
  PK: 'Islamabad',
  PL: 'Warsaw',
  PM: 'Saint-Pierre',
  PN: 'Adamstown',
  PR: 'San Juan',
  PS: 'Ramallah',
  PT: 'Lisbon',
  PW: 'Ngerulmud',
  PY: 'Asunción',
  QA: 'Doha',
  RE: 'Saint-Denis',
  RO: 'Bucharest',
  RS: 'Belgrade',
  RU: 'Moscow',
  RW: 'Kigali',
  SA: 'Riyadh',
  SB: 'Honiara',
  SC: 'Victoria',
  SD: 'Khartoum',
  SE: 'Stockholm',
  SG: 'Singapore',
  SH: 'Jamestown',
  SI: 'Ljubljana',
  SJ: 'Longyearbyen',
  SK: 'Bratislava',
  SL: 'Freetown',
  SM: 'San Marino',
  SN: 'Dakar',
  SO: 'Mogadishu',
  SR: 'Paramaribo',
  SS: 'Juba',
  ST: 'São Tomé',
  SV: 'San Salvador',
  SX: 'Philipsburg',
  SY: 'Damascus',
  SZ: 'Mbabane',
  TC: 'Cockburn Town',
  TD: "N'Djamena",
  TF: 'Port-aux-Français',
  TG: 'Lomé',
  TH: 'Bangkok',
  TJ: 'Dushanbe',
  TK: 'Fakaofo',
  TL: 'Dili',
  TM: 'Ashgabat',
  TN: 'Tunis',
  TO: 'Nukuʻalofa',
  TR: 'Ankara',
  TT: 'Port of Spain',
  TV: 'Funafuti',
  TW: 'Taipei',
  TZ: 'Dodoma',
  UA: 'Kyiv',
  UG: 'Kampala',
  UM: '',
  US: 'Washington, D.C.',
  UY: 'Montevideo',
  UZ: 'Tashkent',
  VA: 'Vatican City',
  VC: 'Kingstown',
  VE: 'Caracas',
  VG: 'Road Town',
  VI: 'Charlotte Amalie',
  VN: 'Hanoi',
  VU: 'Port Vila',
  WF: 'Mata-Utu',
  WS: 'Apia',
  YE: "Sana'a",
  YT: 'Mamoudzou',
  ZA: 'Pretoria',
  ZM: 'Lusaka',
  ZW: 'Harare',
};
